# Exercise 3

In this assignment, you will find numerical solutions to the diffusion equation. In particular, you will use an implicit method, and consider problems with both Dirichlet and Neumann boundary conditions.

**Remember**
   * You are expected to use numpy and scipy libraries where appropriate.  
   * You should run each cell in order from the top of the notebook; there is no need to repeat code between cells
   * Use the "refresh kernel" button to reset everything and start again
   * Make sure your notebook runs fully & without errors, from a fresh kernel, before submitting it

## Problem Overview

The 1D diffusion equation is :

$$\frac{\partial u}{\partial t} = k\frac{\partial^2 u}{\partial x^2}$$

You should discretize this equation onto $N_x$ space points, with separation $\Delta x = h$, and into timesteps $\Delta t = \tau$.  In the equations below, I use subscript $i$ as a space index, and superscript $n$ for time indices.

Having discretized the problem, you should use the _implicit_ finite difference equation, as discussed in lectures :

$$\frac{u_i^{n+1} - u_i^n}{\tau} = k \frac{u_{i+1}^{n+1} - 2u_i^{n+1} + u_{i-1}^{n+1}}{h^2}$$

This can be written in matrix form $u^n = M u^{n+1}$ using :

$$u_i^n = - \alpha u_{i-1}^{n+1} + (1 + 2\alpha) u_i^{n+1} - \alpha u_{i+1}^{n+1}$$

where $\alpha = \frac{k \tau}{h^2}$.

In the problems below, you are asked to solve the diffusion equation in the context of the heat equation. Here, $k$ is the thermal diffusivity, given by $k = \frac{\lambda}{\rho C}$, where $\lambda$ is the thermal conductivity, $\rho$ is the density, and $C$ is the specific heat capacity. The questions below concern an iron poker of length 50cm.  You may take the thermal conductivity of iron to be a constant 59 W/m/K, its specific heat as 450 J/kg/K, and its density as 7,900 kg/m3.  You can ignore heat loss along the length of the poker.


## Part 1 - Dirichlet Boundary Conditions

The poker is initially in equilibrium, at room temperature of 20 C. At time $t = 0$, one end is thrust into a furnace at 1000 C and the other end is held in an ice bath at 0 C. Your task is to calculate the temperature distribution along the poker as a function of time.

The fact that the ends of the rod are held at fixed temperatures of 0 C and 1000 C corresponds to a Dirichlet boundary condition.  These can be included in the implicit method as follows.

The implicit finite difference equation, above, will allow us to calculate the unknown 'internal' nodes, ie. $0 < i < (N_x-1)$.  However, the boundary nodes, $i=0, N_x$, must have fixed values $d_0, d_N$.  To fix the boundaries, we take the matrix M to be of size $(N_x-2) \times (N_x-2)$, and adding a vector term :

$$u^n = Mu^{n+1} + b$$

For $N_x = 7$ (for example), this gives :
$$
M =\begin{pmatrix}
1+2\alpha & -\alpha   &           &           &           & \\
-\alpha   & 1+2\alpha & -\alpha   &           &           & \\
        & -\alpha   & 1+2\alpha & -\alpha   &           & \\
        &           & -\alpha   & 1+2\alpha & -\alpha   & \\
        &           &           & -\alpha   & 1+2\alpha & \\

    \end{pmatrix}
$$

,
$$
b = \begin{pmatrix}
    -\alpha d_0 \\
    0 \\
    0 \\
    0 \\
    -\alpha d_N \\
\end{pmatrix}
$$

You can show this gives the required finite equation for $i=1, (N-1)$, eg. :

$$u^n_1 = - \alpha u^{n+1}_2 + (1 + 2\alpha)u^{n+1}_1 - \alpha d_0$$

First, write functions that will construct the matrix equation and boundary value term.

In [2]:
###### Constructing Matrix Equation and boundary value terms. Will have to generalise this to any size matrices of (N-2)x(N-2) -> (why -2?) 
# Class methods or just functions? 
# create object for certain metal types
# Author - Samuel Hopkins
# Date - January/Febuary 2022

from scipy import linalg, sparse
import numpy as np
import matplotlib.pyplot as plt 
import sys
import time


class Metal:
    """
    Allows me to assign parameters for an arbitrary metal, and then calculate different quantities from them.
    """
    def __init__(self, Name, lamb, rho, C, L):
        self.Name = Name 
        self.lamb = lamb #thermal conductivity
        self.rho = rho  #density
        self.C = C      #Specific Heat
        self.L = L      #Length
        

    def thermaldiffusivity(self):
        return self.lamb / (self.rho * self.C)
        
Iron = Metal('Iron', lamb = 59, rho = 7900, C = 450, L = 0.5)

class Finite_Difference:

    def __init__(self, Name, N, d_0, d_N, tau, h):
        self.N = N
        self.Name = Name
        self.d_0 = d_0
        self.d_N = d_N
        self.tau = tau
        self.h = h #spatial step

def MatrixMaker(N, Metal, tau, h,  identity):
    if Metal == 'test':
        k=1
    else:
        k = Metal.thermaldiffusivity()

    # alpha = (k * FiniteDifference.tau) / (FiniteDifference.h ** 2)
    alpha = (k* tau) / (h**2)
    if identity is True:
        I = sparse.diags([0, 1, 0], [-1, 0, 1], shape = ((N-2, N-2)))
        return I

    elif identity is False:
        M = sparse.diags([-alpha, (1+2*alpha), -alpha], [-1, 0, 1], shape = ((N-2), (N-2)))
        return M.toarray()

def BoundaryCondition(N: int, bc: str, d_0: float, d_N: float) -> np.ndarray:
    alpha = 1
    if bc == 'dirichlet':
        d_N = 273.0 #kelvin
        d_0 = 1273.0
        
        B = np.zeros(N-2)
        B[0] = - alpha * d_0
        B[-1] = - alpha * d_N
        return B

print(MatrixMaker(7, 'test', 1, 1, False ))


print(BoundaryCondition(7, 'dirichlet', d_0 = 1273, d_N = 273))



 

[[ 3. -1.  0.  0.  0.]
 [-1.  3. -1.  0.  0.]
 [ 0. -1.  3. -1.  0.]
 [ 0.  0. -1.  3. -1.]
 [ 0.  0.  0. -1.  3.]]
[-1273.     0.     0.     0.  -273.]


Now write a function which will transport the temperature distribution at time step $n$ to time step $n+1$. You will need to use an appropriate linear algebra routine.

In [3]:

def spatialtransport(N, tau, h, d_0, d_N):
    tau = 0.0001; h = 0.0001
    u_n = np.zeros((N-2, N-2))
    A = MatrixMaker(N, Metal, tau, h, identity=False)
    b = BoundaryCondition(N, Metal, d_0, d_N)

    u_n1 = linalg.spsolve(A, b)
    return u_n1


Finally, use the functions above to calculate the temperature distribution as a function of time, and display this graphically using an appropriate plotting routine.

In [4]:

def temporaltransport(N, maxt, Nx):
    u_n = np.zeros((N-2, N-2))
    for k in range(0, Nx):
        u_n[k] = 20
    
    for _ in range(0, maxt):
        b = u_n
        b[0] = 1000
        b[-1] = 0
        u[:] = spatialtransport(N, tau, h, 1000, 0)

## Part 2 - Neumann Boundary Conditions

Now we assume the far end of the poker from the furnace is no longer held at 0 C, but instead experiences no heat loss. Again your task is to find the tempeterature distribution as a function of time.

In this case, you will need to implement a Neumann boundary condition at the end of the poker, to ensure the derivative $\frac{\partial u}{\partial x}$ is zero. Since we are using finite differences, this is equivalent to ensuring the final two noces have the same value.

The finite difference equation for node $i=(N-1)$ is :

$$u^n_{N-1} = -\alpha u^{n+1}_{N-2} + (1 + 2\alpha)u^{n+1}_{N-1} - \alpha u^{n+1}_{N}$$

To enforce the Neumann boundary condition we can substitute $u^{n+1}_{N} = u^{n+1}_{N-1}$, giving :

$$u^n_{N-1} = -\alpha u^{n+1}_{N-2} + (1 + \alpha)u^{n+1}_{N-1}$$

This results in a modified form of $M$, shown here for the example $N_x=7$, and the matrix ix $5\times5$ :  
\begin{equation}
M = \begin{pmatrix}
1+2\alpha & -\alpha   &           &           &           & \\
-\alpha   & 1+2\alpha & -\alpha   &           &           & \\
          & -\alpha   & 1+2\alpha & -\alpha   &           & \\
          &           & -\alpha   & 1+2\alpha & -\alpha   & \\
          &           &           & -\alpha   & 1+\alpha & \\
\end{pmatrix}
\end{equation}

Note that you will also need to include a boundary term vector $b$, since the end of the poker in the furnace still requires a Dirichlet condition.

First write any new functions you need. You should be able to re-use some functions from Part 1.

Finally, use the functions above to calculate the temperature distribution as a function of time, and display this graphically using a sensible plotting function.

# Part 3

In the Markdown cell below, describe how your code solves the problem set. State any equations used in the solution and how they were obtained. Include your reasons for any libraries you used, as well as any particular programming techniques. Explain your choice of any test cases. Finally, state any salient features of the results you obtained. You are not expected to write more than about 250-300 words.